/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 71f6b38eda6339d80e8809fba73b33bc)
interface __BaseEnv_Env {
	PILOT_EMAIL: SendEmail;
	ASSETS: Fetcher;
	PILOT_DESTINATION_ADDRESS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PILOT_DESTINATION_ADDRESS">> {}
}
