"""stage 0 and walking skeleton schema

Revision ID: 9f78f0e1f10d
Revises:
Create Date: 2026-08-17 21:02:16.939863
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f78f0e1f10d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capabilities',
    sa.Column('canonical_key', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_capability_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_capability_id'], ['capabilities.workspace_id', 'capabilities.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'canonical_key')
    )
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('evaluation_datasets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'name', 'version')
    )
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('processing_jobs',
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('input_versions', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key')
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('external_key', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'name')
    )
    op.create_table('document_versions',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=700), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'document_id'], ['documents.workspace_id', 'documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('workspace_id', 'document_id', 'version_no')
    )
    op.create_table('evaluation_runs',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('implementation_versions', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'dataset_id'], ['evaluation_datasets.workspace_id', 'evaluation_datasets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('product_versions',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=120), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'product_id'], ['products.workspace_id', 'products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'product_id', 'version_label')
    )
    op.create_table('document_representations',
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('parser_contract_version', sa.String(length=40), nullable=False),
    sa.Column('parser_build', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'document_version_id'], ['document_versions.workspace_id', 'document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'document_version_id', 'parser_contract_version', 'content_hash'),
    sa.UniqueConstraint('workspace_id', 'id', 'document_version_id')
    )
    op.create_table('product_version_capabilities',
    sa.Column('product_version_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('support_level', sa.String(length=40), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'capability_id'], ['capabilities.workspace_id', 'capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'product_version_id'], ['product_versions.workspace_id', 'product_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'product_version_id', 'capability_id')
    )
    op.create_table('product_version_documents',
    sa.Column('product_version_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'document_version_id'], ['document_versions.workspace_id', 'document_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'product_version_id'], ['product_versions.workspace_id', 'product_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'product_version_id', 'document_version_id')
    )
    op.create_table('rfps',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_document_version_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_as_of', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requirements_baseline_revision', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'source_document_version_id'], ['document_versions.workspace_id', 'document_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('document_blocks',
    sa.Column('representation_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=False),
    sa.Column('format_locator', sa.JSON(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'representation_id'], ['document_representations.workspace_id', 'document_representations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'representation_id', 'ordinal'),
    sa.UniqueConstraint('workspace_id', 'id', 'representation_id')
    )
    op.create_table('requirements',
    sa.Column('rfp_id', sa.String(length=36), nullable=False),
    sa.Column('source_order', sa.Integer(), nullable=False),
    sa.Column('atomic_text', sa.Text(), nullable=False),
    sa.Column('modality', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('ambiguity_flags', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'rfp_id'], ['rfps.workspace_id', 'rfps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'rfp_id', 'source_order')
    )
    op.create_table('responses',
    sa.Column('rfp_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('assessment_as_of', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'rfp_id'], ['rfps.workspace_id', 'rfps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'rfp_id', 'version_no')
    )
    op.create_table('conflicts',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'requirement_id'], ['requirements.workspace_id', 'requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('evidence',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('product_version_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('authority_level', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieval_rank', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'product_version_id'], ['product_versions.workspace_id', 'product_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'requirement_id'], ['requirements.workspace_id', 'requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('requirement_mappings',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('product_version_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'capability_id'], ['capabilities.workspace_id', 'capabilities.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'product_version_id'], ['product_versions.workspace_id', 'product_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'requirement_id'], ['requirements.workspace_id', 'requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('requirement_source_spans',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('document_block_id', sa.String(length=36), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('exact_quote', sa.Text(), nullable=False),
    sa.Column('quote_hash', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'document_block_id'], ['document_blocks.workspace_id', 'document_blocks.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'requirement_id'], ['requirements.workspace_id', 'requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('response_exports',
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=700), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'response_id'], ['responses.workspace_id', 'responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_table('compliance_decisions',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('product_version_id', sa.String(length=36), nullable=False),
    sa.Column('mapping_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('policy_required', sa.Boolean(), nullable=False),
    sa.Column('assessment_as_of', sa.Date(), nullable=False),
    sa.Column('scope_valid_from', sa.Date(), nullable=True),
    sa.Column('scope_valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'mapping_id'], ['requirement_mappings.workspace_id', 'requirement_mappings.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'product_version_id'], ['product_versions.workspace_id', 'product_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'requirement_id'], ['requirements.workspace_id', 'requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'supersedes_id'], ['compliance_decisions.workspace_id', 'compliance_decisions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('evidence_spans',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('representation_id', sa.String(length=36), nullable=False),
    sa.Column('document_block_id', sa.String(length=36), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('exact_quote', sa.Text(), nullable=False),
    sa.Column('quote_hash', sa.String(length=64), nullable=False),
    sa.Column('format_locator', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'document_block_id'], ['document_blocks.workspace_id', 'document_blocks.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'document_block_id', 'representation_id'], ['document_blocks.workspace_id', 'document_blocks.id', 'document_blocks.representation_id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'document_version_id'], ['document_versions.workspace_id', 'document_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'evidence_id'], ['evidence.workspace_id', 'evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'representation_id'], ['document_representations.workspace_id', 'document_representations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'representation_id', 'document_version_id'], ['document_representations.workspace_id', 'document_representations.id', 'document_representations.document_version_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('decision_evidence_spans',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_span_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_id'], ['compliance_decisions.workspace_id', 'compliance_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'evidence_span_id'], ['evidence_spans.workspace_id', 'evidence_spans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'decision_id', 'evidence_span_id')
    )
    op.create_table('human_reviews',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_subject', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_id'], ['compliance_decisions.workspace_id', 'compliance_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id')
    )
    op.create_table('response_items',
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('source_order', sa.Integer(), nullable=False),
    sa.Column('item_json', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_id'], ['compliance_decisions.workspace_id', 'compliance_decisions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'requirement_id'], ['requirements.workspace_id', 'requirements.id'], ),
    sa.ForeignKeyConstraint(['workspace_id', 'response_id'], ['responses.workspace_id', 'responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'id'),
    sa.UniqueConstraint('workspace_id', 'response_id', 'source_order')
    )
    if op.get_bind().dialect.name == 'postgresql':
        workspace_tables = [
            'capabilities', 'compliance_decisions', 'conflicts', 'decision_evidence_spans',
            'document_blocks', 'document_representations', 'document_versions', 'documents',
            'evaluation_datasets', 'evaluation_runs', 'evidence', 'evidence_spans',
            'human_reviews', 'outbox_events', 'processing_jobs',
            'product_version_capabilities', 'product_version_documents', 'product_versions',
            'products', 'requirement_mappings', 'requirement_source_spans', 'requirements',
            'response_exports', 'response_items', 'responses', 'rfps',
        ]
        for table in workspace_tables:
            op.execute(sa.text(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY'))
            op.execute(sa.text(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY'))
            op.execute(sa.text(
                f"CREATE POLICY workspace_isolation ON {table} "
                "USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')) "
                "WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), ''))"
            ))

        op.execute(sa.text("""
            CREATE FUNCTION ctrl_reject_document_version_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'DocumentVersion is immutable';
            END;
            $$ LANGUAGE plpgsql
        """))
        op.execute(sa.text("""
            CREATE TRIGGER document_versions_immutable
            BEFORE UPDATE OR DELETE ON document_versions
            FOR EACH ROW EXECUTE FUNCTION ctrl_reject_document_version_mutation()
        """))
        op.execute(sa.text("""
            CREATE FUNCTION ctrl_reject_approved_decision_mutation() RETURNS trigger AS $$
            BEGIN
                IF OLD.status = 'APPROVED' THEN
                    RAISE EXCEPTION 'Approved ComplianceDecision is immutable';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """))
        op.execute(sa.text("""
            CREATE TRIGGER approved_decisions_immutable
            BEFORE UPDATE OR DELETE ON compliance_decisions
            FOR EACH ROW EXECUTE FUNCTION ctrl_reject_approved_decision_mutation()
        """))
        op.execute(sa.text("""
            CREATE FUNCTION ctrl_validate_decision_evidence() RETURNS trigger AS $$
            BEGIN
                IF NEW.status = 'APPROVED'
                   AND NEW.outcome IN ('COMPLY', 'PARTIAL')
                   AND NOT EXISTS (
                       SELECT 1 FROM decision_evidence_spans links
                       JOIN evidence_spans spans
                         ON spans.workspace_id = links.workspace_id
                        AND spans.id = links.evidence_span_id
                       JOIN document_versions versions
                         ON versions.workspace_id = spans.workspace_id
                        AND versions.id = spans.document_version_id
                       WHERE links.workspace_id = NEW.workspace_id
                         AND links.decision_id = NEW.id
                   ) THEN
                    RAISE EXCEPTION 'APPROVED COMPLY/PARTIAL requires an exact EvidenceSpan';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """))
        op.execute(sa.text("""
            CREATE CONSTRAINT TRIGGER approved_decision_requires_evidence
            AFTER INSERT OR UPDATE ON compliance_decisions
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION ctrl_validate_decision_evidence()
        """))
        op.execute(sa.text("""
            CREATE FUNCTION ctrl_protect_approved_decision_links() RETURNS trigger AS $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM compliance_decisions decisions
                    WHERE decisions.workspace_id = OLD.workspace_id
                      AND decisions.id = OLD.decision_id
                      AND decisions.status = 'APPROVED'
                ) THEN
                    RAISE EXCEPTION 'Evidence links of an approved decision are immutable';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """))
        op.execute(sa.text("""
            CREATE TRIGGER approved_decision_links_immutable
            BEFORE UPDATE OR DELETE ON decision_evidence_spans
            FOR EACH ROW EXECUTE FUNCTION ctrl_protect_approved_decision_links()
        """))
        op.execute(sa.text("""
            CREATE FUNCTION ctrl_protect_response_snapshot() RETURNS trigger AS $$
            BEGIN
                IF OLD.snapshot_hash IS DISTINCT FROM NEW.snapshot_hash
                   OR OLD.snapshot_json IS DISTINCT FROM NEW.snapshot_json
                   OR OLD.rfp_id IS DISTINCT FROM NEW.rfp_id
                   OR OLD.assessment_as_of IS DISTINCT FROM NEW.assessment_as_of
                   OR OLD.version_no IS DISTINCT FROM NEW.version_no THEN
                    RAISE EXCEPTION 'Response snapshot is immutable';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """))
        op.execute(sa.text("""
            CREATE TRIGGER response_snapshot_immutable
            BEFORE UPDATE ON responses
            FOR EACH ROW EXECUTE FUNCTION ctrl_protect_response_snapshot()
        """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP FUNCTION IF EXISTS ctrl_protect_response_snapshot() CASCADE')
        op.execute('DROP FUNCTION IF EXISTS ctrl_protect_approved_decision_links() CASCADE')
        op.execute('DROP FUNCTION IF EXISTS ctrl_validate_decision_evidence() CASCADE')
        op.execute('DROP FUNCTION IF EXISTS ctrl_reject_approved_decision_mutation() CASCADE')
        op.execute('DROP FUNCTION IF EXISTS ctrl_reject_document_version_mutation() CASCADE')
    op.drop_table('response_items')
    op.drop_table('human_reviews')
    op.drop_table('decision_evidence_spans')
    op.drop_table('evidence_spans')
    op.drop_table('compliance_decisions')
    op.drop_table('response_exports')
    op.drop_table('requirement_source_spans')
    op.drop_table('requirement_mappings')
    op.drop_table('evidence')
    op.drop_table('conflicts')
    op.drop_table('responses')
    op.drop_table('requirements')
    op.drop_table('document_blocks')
    op.drop_table('rfps')
    op.drop_table('product_version_documents')
    op.drop_table('product_version_capabilities')
    op.drop_table('document_representations')
    op.drop_table('product_versions')
    op.drop_table('evaluation_runs')
    op.drop_table('document_versions')
    op.drop_table('products')
    op.drop_table('processing_jobs')
    op.drop_table('outbox_events')
    op.drop_table('evaluation_datasets')
    op.drop_table('documents')
    op.drop_table('capabilities')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
